/**
 * Offline trainer for the Fly's shipped brain. Skipped in the normal test run;
 * run it with `npm run train:fly` (FLY_TRAIN=1, optional FLY_TRAIN_GAMES=N).
 *
 * The fly plays N games against Normal and Hard CPUs (alternating opponent and
 * seat), learning into one brain throughout, then writes that brain to
 * `trainedFlyBrain.ts`, which the game starts every fly from. Training seeds
 * start at 10001 so they never overlap the 1–200 used to benchmark it.
 */

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { it } from 'vitest';
import type { AiDifficulty } from '../types';
import { applyAction, chooseAiAction, createAiMemory, createGame, isGameOver } from '../index';
import { createFlyBrain, finishFlyGames } from './fly';

const TRAIN = process.env.FLY_TRAIN === '1';
const GAMES = Number(process.env.FLY_TRAIN_GAMES ?? 1000);

it.skipIf(!TRAIN)(
  `trains the shipped fly brain over ${GAMES} games`,
  () => {
    const brain = createFlyBrain();
    let wins = 0;
    for (let g = 0; g < GAMES; g++) {
      const seed = 10001 + g;
      const flySeat = g % 2;
      const opponent: AiDifficulty = g % 4 < 2 ? 'normal' : 'hard';
      const memory = createAiMemory({ flyBrain: brain, flyLearn: true });
      const players = [0, 1].map((i) => ({
        name: `P${i}`,
        controller: 'cpu' as const,
        difficulty: i === flySeat ? ('fly' as const) : opponent,
      }));
      let s = createGame({ players, gardenPreset: 'random' }, seed);
      for (let i = 0; i < 10_000 && !isGameOver(s); i++) s = applyAction(s, chooseAiAction(s, memory));
      finishFlyGames(s, memory.fly);
      if (s.winner === flySeat) wins += 1;
    }

    const values = Object.fromEntries(
      Object.entries(brain.values)
        .sort(([a], [b]) => (a < b ? -1 : 1))
        .map(([k, v]) => [k, Math.round(v * 1000) / 1000]),
    );
    const out = fileURLToPath(new URL('./trainedFlyBrain.ts', import.meta.url));
    writeFileSync(
      out,
      `/**
 * The brain every Fly starts from — GENERATED by \`npm run train:fly\`
 * (fly.train.test.ts); do not edit by hand. Trained over ${GAMES} games against
 * Normal and Hard CPUs, winning ${wins}.
 */

import type { FlyBrain } from './fly';

export const TRAINED_FLY_BRAIN: FlyBrain = ${JSON.stringify({ version: 2, gamesPlayed: brain.gamesPlayed, values }, null, 2)};
`,
    );
    console.log(`fly won ${wins}/${GAMES} while training; wrote ${out}`);
  },
  3_600_000,
);
