/**
 * The brain every Fly starts from — GENERATED by `npm run train:fly`
 * (fly.train.test.ts); do not edit by hand.
 *
 * Currently BLANK on purpose. A brain trained over 1000 self-play games made
 * the fly weaker on the benchmark (72 vs 91 wins out of 200 against Normal):
 * the learning rule credits the short-term rewards (planting, harvests, draws)
 * and learns to stop advancing, whose payoff arrives too late for its traces.
 * Regenerate with `FLY_TRAIN_GAMES=1000 npm run train:fly` once training beats
 * a blank brain on the benchmark.
 */

import type { FlyBrain } from './fly';

export const TRAINED_FLY_BRAIN: FlyBrain = {
  "version": 1,
  "gamesPlayed": 0,
  "values": {}
};
