/**
 * The brain every Fly starts from — GENERATED by `npm run train:fly`
 * (fly.train.test.ts); do not edit by hand.
 *
 * Currently BLANK on purpose: no learned brain has yet beaten a fly that
 * never learns. On the 200-game benchmark against Normal, the non-learning fly
 * wins 86; a 1000-game post-game-review brain wins 67 (and a live-learning
 * brain before it, 72). Regenerate with `FLY_TRAIN_GAMES=1000 npm run
 * train:fly` once training beats that.
 */

import type { FlyBrain } from './fly';

export const TRAINED_FLY_BRAIN: FlyBrain = {
  "version": 2,
  "gamesPlayed": 0,
  "values": {}
};
