/**
 * Win-rate-tuned overrides for the Fly's settings — GENERATED by
 * `npm run tune:fly` (scripts/tune-fly.mjs); do not edit by hand. `null` =
 * use the hand-set defaults in fly.ts and flyIntent.ts.
 *
 * Currently null on purpose. A 16-round tune reached 90 of 200 on its own
 * pool (defaults 78), but on the held-out benchmark (seeds 1–200) the tuned
 * settings won 83 vs Normal and 83 vs Hard against the defaults' 85 and 84:
 * the gain was selection noise (adopting the best of four noisy scores each
 * round). Re-checking each adopted candidate on fresh games would fix that.
 */

import type { FlyTag } from './fly';

export interface TunedFlyParams {
  priority?: Partial<Record<FlyTag, number>>;
  fightOdds?: number[];
  threat?: Record<string, number>;
  intent?: Record<string, number>;
}

export const TUNED_FLY_PARAMS: TunedFlyParams | null = null;
