/**
 * Win-rate-tuned overrides for the Fly's settings — GENERATED by
 * `npm run tune:fly` (scripts/tune-fly.mjs); do not edit by hand. `null` =
 * use the hand-set defaults in fly.ts and flyIntent.ts.
 *
 * On the tuning pool (200 games vs Normal/Hard) these won 83; the
 * hand-set defaults won 78.
 */

import type { FlyTag } from './fly';

export interface TunedFlyParams {
  priority?: Partial<Record<FlyTag, number>>;
  fightOdds?: number[];
  threat?: Record<string, number>;
  intent?: Record<string, number>;
}

export const TUNED_FLY_PARAMS: TunedFlyParams | null = {
  "priority": {
    "territory": 1.5,
    "plant": 1.25,
    "harvest": 1,
    "card": 0.6,
    "draw": 0.3,
    "fight": 0.75,
    "advance": 1.5,
    "defend": 3.5
  },
  "fightOdds": [
    0.4,
    0.62,
    0.85
  ],
  "threat": {
    "radius": 2,
    "alarmAt": 2,
    "oddsRelief": 0.1
  },
  "intent": {
    "anticipateAt": 0.6,
    "interceptAt": 0.5,
    "counterattack": 1.5,
    "progressWeight": 1.5,
    "distanceWeight": 0.35
  }
};
