"""Pack circuit/flyCircuit.json into the game's TypeScript data module.

    flybrain/.venv/bin/python flybrain/export_circuit_ts.py OUT.ts

The connections are stored compactly: grouped by presynaptic neuron (CSR),
targets as little-endian uint16 and signed synapse counts as int16, each
base64-encoded. `response` is the whole-brain output table the cut was
validated against, for the game's own simulator test.
"""

import base64
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent


def b64(a: np.ndarray) -> str:
    return base64.b64encode(a.astype(a.dtype.newbyteorder("<")).tobytes()).decode()


def main() -> None:
    c = json.loads((HERE / "circuit" / "flyCircuit.json").read_text())
    n = c["neurons"]
    assert n < 65536
    pre = np.array(c["pre"], dtype=np.int64)
    order = np.argsort(pre, kind="stable")
    targets = np.array(c["post"], dtype=np.uint16)[order]
    weights = np.clip(np.array(c["weight"], dtype=np.int64), -32768, 32767).astype(np.int16)[order]
    start = np.zeros(n + 1, dtype=np.int32)
    np.add.at(start, pre + 1, 1)
    start = np.cumsum(start).astype(np.int32)
    data = {
        "source": c["source"],
        "validation": c["validation"],
        "neurons": n,
        "params": c["params"],
        "channels": c["channels"],
        "start": b64(start),
        "targets": b64(targets),
        "weights": b64(weights),
        "response": c["response"],
    }
    out = Path(sys.argv[1])
    out.write_text(
        "/**\n"
        " * The Fly's circuit, cut from the FlyWire v783 connectome — GENERATED by\n"
        " * flybrain/export_circuit_ts.py in the Gnome-ConquestWhimsy-Wars-FlyBrain\n"
        " * repository; do not edit. See flyBrain.ts for how the game uses it.\n"
        " *\n"
        f" * {n:,} neurons and {len(pre):,} connections. Connectome: FlyWire (Dorkenwald et al.\n"
        " * 2024, Schlegel et al. 2024) — credit FlyWire and check its terms at\n"
        " * https://flywire.ai before distributing; model after Shiu et al. 2024 (MIT).\n"
        " */\n\n"
        "import type { CircuitData } from './flySim';\n\n"
        f"export const FLY_CIRCUIT: CircuitData = {json.dumps(data, separators=(',', ':'))};\n"
    )
    print(f"wrote {out} ({out.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
