#!/usr/bin/env node
/**
 * Win-rate tuner for the Fly's settings: `npm run tune:fly`.
 *
 * Hill climbing. Each round proposes CANDIDATES variations of the current best
 * settings (1–3 settings nudged by one step each), plays every candidate over
 * the same fixed pool of games in parallel (src/engine/ai/fly.tune.test.ts),
 * and adopts the best one only if it beats the current best by MARGIN wins.
 * The winner is written to src/engine/ai/tunedFlyParams.ts after every round,
 * so stopping early keeps the progress so far.
 *
 * Env: FLY_TUNE_ROUNDS (20), FLY_TUNE_CANDIDATES (4), FLY_TUNE_GAMES (200),
 * FLY_TUNE_MARGIN (3), FLY_TUNE_SEED (1).
 *
 * Deterministic given its seed: the proposals come from a seeded generator.
 */

import { spawn } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const ROUNDS = Number(process.env.FLY_TUNE_ROUNDS ?? 20);
const CANDIDATES = Number(process.env.FLY_TUNE_CANDIDATES ?? 4);
const GAMES = Number(process.env.FLY_TUNE_GAMES ?? 200);
const MARGIN = Number(process.env.FLY_TUNE_MARGIN ?? 3);
let rng = Number(process.env.FLY_TUNE_SEED ?? 1) >>> 0;

/** The search space: [group, key, min, max, step]. Defaults are fly.ts's. */
const SPACE = [
  ['priority', 'territory', 0, 5, 0.5],
  ['priority', 'plant', 0, 5, 0.5],
  ['priority', 'harvest', 0, 5, 0.5],
  ['priority', 'card', 0, 3, 0.3],
  ['priority', 'draw', 0, 2, 0.2],
  ['priority', 'fight', 0, 4, 0.5],
  ['priority', 'advance', 0, 5, 0.5],
  ['priority', 'defend', 0, 6, 0.5],
  ['fightOdds', 0, 0.2, 0.7, 0.05],
  ['fightOdds', 1, 0.35, 0.9, 0.05],
  ['fightOdds', 2, 0.5, 1, 0.05],
  ['threat', 'radius', 1, 4, 1],
  ['threat', 'alarmAt', 1, 4, 1],
  ['threat', 'oddsRelief', 0, 0.3, 0.05],
  ['intent', 'anticipateAt', 0.2, 1.5, 0.1],
  ['intent', 'interceptAt', 0.2, 0.9, 0.1],
  ['intent', 'counterattack', 0, 4, 0.5],
  ['intent', 'progressWeight', 0, 3, 0.5],
  ['intent', 'distanceWeight', 0, 1, 0.1],
];

const DEFAULTS = {
  priority: { territory: 1.5, plant: 1.25, harvest: 1, card: 0.6, draw: 0.3, fight: 0.75, advance: 1.5, defend: 3 },
  fightOdds: [0.4, 0.62, 0.85],
  threat: { radius: 2, alarmAt: 2, oddsRelief: 0.1 },
  intent: { anticipateAt: 0.6, interceptAt: 0.5, counterattack: 1.5, progressWeight: 1.5, distanceWeight: 0.35 },
};

function random() {
  rng = (Math.imul(rng, 1664525) + 1013904223) >>> 0;
  return rng / 2 ** 32;
}

function mutate(params) {
  const next = structuredClone(params);
  const changes = [];
  const n = 1 + Math.floor(random() * 3);
  for (let i = 0; i < n; i++) {
    const [group, key, min, max, step] = SPACE[Math.floor(random() * SPACE.length)];
    const old = next[group][key];
    const v = Math.round(Math.min(max, Math.max(min, old + (random() < 0.5 ? -step : step))) * 1000) / 1000;
    next[group][key] = v;
    changes.push(`${group}.${key} ${old}→${v}`);
  }
  // Keep the fight bars rising: a 2nd fight never needs worse odds than the 1st.
  const o = next.fightOdds;
  o[1] = Math.max(o[1], o[0]);
  o[2] = Math.max(o[2], o[1]);
  return { params: next, changes };
}

const dir = mkdtempSync(join(tmpdir(), 'fly-tune-'));
let job = 0;

/** Evaluate, retrying once: a parallel run can occasionally die for lack of resources. */
async function evaluate(params) {
  try {
    return await evaluateOnce(params);
  } catch (err) {
    console.log(`retrying after: ${err.message}`);
    return evaluateOnce(params);
  }
}

function evaluateOnce(params) {
  const id = job++;
  const paramsFile = join(dir, `p${id}.json`);
  const outFile = join(dir, `r${id}.json`);
  writeFileSync(paramsFile, JSON.stringify(params));
  return new Promise((resolve, reject) => {
    const child = spawn('npx', ['vitest', 'run', 'src/engine/ai/fly.tune.test.ts'], {
      env: { ...process.env, FLY_TUNE_PARAMS: paramsFile, FLY_TUNE_OUT: outFile, FLY_TUNE_GAMES: String(GAMES) },
      stdio: ['ignore', 'ignore', 'pipe'],
    });
    let stderr = '';
    child.stderr.on('data', (d) => (stderr += d));
    child.on('exit', (code) => {
      if (code !== 0) reject(new Error(`evaluator exited ${code}: ${stderr.slice(-400)}`));
      else resolve(JSON.parse(readFileSync(outFile, 'utf8')).wins);
    });
  });
}

function writeTuned(params, wins, baseline) {
  writeFileSync(
    new URL('../src/engine/ai/tunedFlyParams.ts', import.meta.url),
    `/**
 * Win-rate-tuned overrides for the Fly's settings — GENERATED by
 * \`npm run tune:fly\` (scripts/tune-fly.mjs); do not edit by hand. \`null\` =
 * use the hand-set defaults in fly.ts and flyIntent.ts.
 *
 * On the tuning pool (${GAMES} games vs Normal/Hard) these won ${wins}; the
 * hand-set defaults won ${baseline}.
 */

import type { FlyTag } from './fly';

export interface TunedFlyParams {
  priority?: Partial<Record<FlyTag, number>>;
  fightOdds?: number[];
  threat?: Record<string, number>;
  intent?: Record<string, number>;
}

export const TUNED_FLY_PARAMS: TunedFlyParams | null = ${JSON.stringify(params, null, 2)};
`,
  );
}

// FLY_TUNE_RESUME=1 continues from the settings in tunedFlyParams.ts.
const TUNED = new URL('../src/engine/ai/tunedFlyParams.ts', import.meta.url);
let best = DEFAULTS;
let baseline = null;
if (process.env.FLY_TUNE_RESUME === '1') {
  const src = readFileSync(TUNED, 'utf8');
  const json = src.slice(src.indexOf('= ', src.indexOf('TUNED_FLY_PARAMS:')) + 2, src.lastIndexOf(';'));
  if (json.trim() !== 'null') best = JSON.parse(json);
  const m = src.match(/hand-set defaults won (\d+)/);
  if (m) baseline = Number(m[1]);
}
let bestWins = await evaluate(best);
baseline ??= bestWins;
console.log(`start: ${bestWins}/${GAMES} (defaults ${baseline})`);

for (let round = 1; round <= ROUNDS; round++) {
  const proposals = Array.from({ length: CANDIDATES }, () => mutate(best));
  const scores = await Promise.all(proposals.map((p) => evaluate(p.params)));
  let top = 0;
  for (let i = 1; i < scores.length; i++) if (scores[i] > scores[top]) top = i;
  const line = proposals.map((p, i) => `${scores[i]} [${p.changes.join(', ')}]`).join(' | ');
  if (scores[top] >= bestWins + MARGIN) {
    best = proposals[top].params;
    bestWins = scores[top];
    writeTuned(best, bestWins, baseline);
    console.log(`round ${round}: ADOPTED ${bestWins} — ${line}`);
  } else {
    console.log(`round ${round}: kept ${bestWins} — ${line}`);
  }
}
console.log(`done: ${bestWins}/${GAMES} (defaults ${baseline})`);
console.log(JSON.stringify(best));
